name: mailfix
description: Package for email validation with domain correction suggestions using configurable similarity algorithms.
version: 0.37.1
repository: https://github.com/ValdirGiorgi/mailfix
homepage: https://github.com/ValdirGiorgi/mailfix
issue_tracker: https://github.com/ValdirGiorgi/mailfix/issues

screenshots:
  - description: The dart package mailfix provides a function to validate email addresses and suggest corrections for common domain typos.
    path: assets/logos/mailfix.png

environment:
  sdk: ^3.7.0

dependencies:
  email_validator: ^3.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8

topics:
  - email
  - validation
  - domain-correction
  - levenshtein
  - jaro-winkler
